spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_sampledb?serverTimezone=JST
    username: root
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update